Repository 100-hours-a-week/3-team-modie-fe, pull requests merged in 2025-04, with the labels that each got.

#64 ✨ Fix - 새로고침, 이전페이지 이동에서도 모임 생성 데이터 유지
  dev-dist/sw.js
  src/main/page/Main.tsx
  src/meetCreate(update)/hooks/useCreateMeetOther.tsx
  src/meetCreate(update)/hooks/useCreateMeetPlace.tsx
  src/meetCreate(update)/page/CreateMeetOther.tsx
  src/meetCreate(update)/page/CreateMeetPlace.tsx
  src/meetCreate(update)/store/useCreateMeetStore.ts
Labels: 버그-일반

#65 ✨ Fix - 모임 나가기 모달의 텍스트 수정
  dev-dist/sw.js
  src/common/hooks/useHeaderContirmModal.tsx
  src/utils/getModalText.ts
Labels: 버그-일반

#66 ✨ Fix - 처음 페이지 접근 시 스플래쉬 화면이 조금 늦게 로딩됨
  dev-dist/sw.js
  src/main/hooks/useMeetData.tsx
  src/main/page/Main.tsx
Labels: 버그-일반

#67 ✨ Fix - 모임 생성 지도 보다 토스트 메세지가 아래에 표시되는 문제 해결
  dev-dist/sw.js
  src/common/components/ToastMsg.tsx
  src/meetCreate(update)/page/CreateMeetPlace.tsx
Labels: 버그-일반

#74 🐛 FIX - 모임 수정시 데이터 입력이 먹지 않는 오류 픽스
  public/firebase-messaging-sw.js
  src/__fcm__/fcm.ts
  src/login/page/LoginRedirect.tsx
  src/main.tsx
  src/meetCreate(update)/hooks/useCreateMeetOther.tsx
Labels: 버그-심각

#77 🐛 Fix - 채팅 시간 조정 삭제
  src/meetChat/hooks/useChatSocket.tsx
  src/utils/formatChatDate.ts
Labels: 버그-일반

#80 🐛 Fix - 메인 페이지에 모임이 없는 경우의 텍스트가 잠깐 보였다가 사라지는 오류 픽스
  src/main/page/Main.tsx
Labels: 버그-일반

#82 🐛 Fix - 현재 모인 인원보다 적은 인원으로 모임 인원 수정이 가능한 오류 픽스
  package.json
  src/meetCreate(update)/hooks/useCreateMeetOther.tsx
  src/meetCreate(update)/store/useCreateMeetStore.ts
  src/utils/convertMeetTypeToMeetInfo.ts
  yarn.lock
Labels: 버그-일반

#83 🔀 Release - dev 브랜치 병합
  .github/workflows/cicd-prod.yml
  .github/workflows/cicd.yml
  CHANGELOG.md
  dev-dist/sw.js
  firebase.ts
  index.html
  package.json
  public/firebase-messaging-sw.js
  public/logo.png
  src/__fcm__/fcm.ts
  src/common/components/Header.tsx
  src/common/components/ToastMsg.tsx
  src/common/hooks/useHeaderContirmModal.tsx
  src/common/types/meetType.ts
  src/login/page/LoginRedirect.tsx
  src/login/services/postFcmService.ts
  src/login/types/postFcmRequest.ts
  src/login/types/postFcmResponse.ts
  src/main.tsx
  src/main/hooks/useMeetCardData.tsx
  src/main/hooks/useMeetData.tsx
  src/main/page/Main.tsx
  src/meetChat/hooks/useChat.tsx
  src/meetChat/hooks/useChatSocket.tsx
  src/meetCreate(update)/hooks/useCreateMeetOther.tsx
  src/meetCreate(update)/hooks/useCreateMeetPlace.tsx
  src/meetCreate(update)/page/CreateMeetOther.tsx
  src/meetCreate(update)/page/CreateMeetPlace.tsx
  src/meetCreate(update)/services/updateMeetService.ts
  src/meetCreate(update)/store/useCreateMeetStore.ts
  src/meetCreate(update)/types/createMeetResponse.ts
  src/meetCreate(update)/types/updateMeetResponse.ts
  src/meetDetail/hooks/useMeetStore.tsx
  src/meetDetail/page/MeetDetail.tsx
  src/meetDetail/services/completeMeetService.tsx
  src/meetDetail/services/deleteMeetService.tsx
  src/meetDetail/services/exitMeetService.tsx
  src/meetDetail/services/getMeetDetailService.tsx
  src/meetDetail/services/joinMeetService.tsx
  src/meetDetail/services/updatePaymentService.tsx
  src/meetPaying/services/updateAmountService.ts
  src/my/hooks/useMyPage.tsx
  src/utils/convertMeetTypeToMeetInfo.ts
  src/utils/formatChatDate.ts
  src/utils/getModalText.ts
  sw.js
  yarn.lock
Labels: released

#86 🐛 Fix - 로그아웃시 FCM 토큰 비동기 삭제 처리
  src/my/hooks/useMyPage.tsx
Labels: 버그-일반

#91 fix: 모임 생성 버튼이 안 보이는 문제 해결 (긴급!)
  src/main/components/CreateButton.tsx
Labels: 버그-일반

#92 🔀 Release - dev 브랜치 병합
  CHANGELOG.md
  src/main/components/CreateButton.tsx
Labels: 버그-일반, released on @dev

#94 🐛 Fix - 모임 삭제/종료/나가기 alert 제거, 모임 생성 단계에서 좌표의 주소가 즉각적으로 업데이트 되지 않는 오류 픽스 외 3건
  src/common/components/Header.tsx
  src/common/hooks/useHeaderContirmModal.tsx
  src/meetCreate(update)/components/LoadingMap.tsx
  src/meetCreate(update)/components/MarkerInfoWindow.tsx
  src/meetCreate(update)/hooks/useCreateMeetPlace.tsx
  src/meetCreate(update)/page/CreateMeetPlace.tsx
  src/meetDetail/services/completeMeetService.tsx
  src/router.tsx
Labels: 버그-일반

#97 🔀 Release - dev 브랜치 병합
  CHANGELOG.md
  src/common/components/Header.tsx
  src/common/hooks/useHeaderContirmModal.tsx
  src/meetCreate(update)/components/LoadingMap.tsx
  src/meetCreate(update)/components/MarkerInfoWindow.tsx
  src/meetCreate(update)/hooks/useCreateMeetPlace.tsx
  src/meetCreate(update)/page/CreateMeetPlace.tsx
  src/meetDetail/services/completeMeetService.tsx
  src/router.tsx
Labels: released

#99 🐛 Hotfix - 주소가 마커 인포위도우를 벗어나는 오류, 모임 상세 페이지에서 로그인 후 메인 페이지로 리다이렉트 되는 오류 픽스 (긴급!)
  dev-dist/sw.js
  src/common/components/Header.tsx
  src/meetCreate(update)/components/MarkerInfoWindow.tsx
Labels: 버그-일반

#100 🔀 Release - dev 브랜치 병합
  CHANGELOG.md
  dev-dist/sw.js
  src/common/components/Header.tsx
  src/meetCreate(update)/components/MarkerInfoWindow.tsx
Labels: released on @dev
