Repository 100-hours-a-week/3-team-modie-fe, pull requests merged in 2025-03, with the labels that each got.

#40 ✨ Feature - 채팅 엔터키 구현 및 채팅 시간 오류 수정
  dev-dist/sw.js
  src/meetChat/components/chatInput.tsx
  src/meetChat/hooks/useChatSocket.tsx
  src/utils/formatChatDate.ts
Labels: 버그-일반

#45 🔀 Release - dev 브랜치 병합
  .github/workflows/cicd-prod.yml
  .github/workflows/cicd.yml
  CHANGELOG.md
  dev-dist/sw.js
  index.html
  package.json
  src/login/page/LoginRedirect.tsx
  src/main.tsx
  src/meetDetail/page/MeetDetail.tsx
  yarn.lock
Labels: released on @dev, released

#50 🔀 Release - dev 브랜치 병합
  src/meetCreate(update)/hooks/useCreateMeetOther.tsx
Labels: released

#54 🐛 Fix - 멤버의 정산 내역 업데이트 토글 관련 에러 픽스
  dev-dist/sw.js
  src/common/types/meetType.ts
  src/meetDetail/components/Toggle.tsx
  src/meetDetail/hooks/useDebouncedToggle.tsx
  src/meetDetail/page/MeetDetail.tsx
Labels: 버그-일반

#56 🐛 Fix - 모임 생성 후 모임 생성에 사용된 데이터 초기화 처리, 모임 생성 후 중복 토스트 메세지가 보이는 에러 픽스, 모임 생성시 지도 최대 줌아웃 설정, 비용이 발생하지 않는 모임의 비용 섹션 숨김 처리
  src/meetCreate(update)/hooks/useCreateMeetSubmit.ts
  src/meetCreate(update)/page/CreateMeetPlace.tsx
  src/meetDetail/components/KakaoMap.tsx
  src/meetDetail/page/MeetDetail.tsx
Labels: 버그-일반

#59 🔀 Release - dev 브랜치 병합
  dev-dist/sw.js
  src/common/types/meetType.ts
  src/main/hooks/useMeetData.tsx
  src/main/page/Main.tsx
  src/meetCreate(update)/hooks/useCreateMeetOther.tsx
  src/meetCreate(update)/hooks/useCreateMeetSubmit.ts
  src/meetCreate(update)/page/CreateMeetOther.tsx
  src/meetCreate(update)/page/CreateMeetPlace.tsx
  src/meetDetail/components/KakaoMap.tsx
  src/meetDetail/components/Toggle.tsx
  src/meetDetail/hooks/useDebouncedToggle.tsx
  src/meetDetail/page/MeetDetail.tsx
Labels: released
